[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
